/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from "@adonisjs/lucid/orm";
import type { DateTime } from "luxon";

export class QueueJobSchema extends BaseModel {
	static $columns = [
		"acquiredAt",
		"data",
		"dedupAt",
		"dedupId",
		"dedupTtl",
		"error",
		"executeAt",
		"finishedAt",
		"id",
		"queue",
		"score",
		"status",
		"workerId",
	] as const;
	$columns = QueueJobSchema.$columns;
	@column()
	declare acquiredAt: bigint | number | null;
	@column()
	declare data: string;
	@column()
	declare dedupAt: bigint | number | null;
	@column()
	declare dedupId: string | null;
	@column()
	declare dedupTtl: bigint | number | null;
	@column()
	declare error: string | null;
	@column()
	declare executeAt: bigint | number | null;
	@column()
	declare finishedAt: bigint | number | null;
	@column({ isPrimary: true })
	declare id: string;
	@column()
	declare queue: string;
	@column()
	declare score: bigint | number | null;
	@column()
	declare status: string;
	@column()
	declare workerId: string | null;
}

export class QueueScheduleSchema extends BaseModel {
	static $columns = [
		"createdAt",
		"cronExpression",
		"everyMs",
		"fromDate",
		"id",
		"lastRunAt",
		"name",
		"nextRunAt",
		"payload",
		"runCount",
		"runLimit",
		"status",
		"timezone",
		"toDate",
	] as const;
	$columns = QueueScheduleSchema.$columns;
	@column.dateTime({ autoCreate: true })
	declare createdAt: DateTime;
	@column()
	declare cronExpression: string | null;
	@column()
	declare everyMs: bigint | number | null;
	@column.dateTime()
	declare fromDate: DateTime | null;
	@column({ isPrimary: true })
	declare id: string;
	@column.dateTime()
	declare lastRunAt: DateTime | null;
	@column()
	declare name: string;
	@column.dateTime()
	declare nextRunAt: DateTime | null;
	@column()
	declare payload: string;
	@column()
	declare runCount: number;
	@column()
	declare runLimit: number | null;
	@column()
	declare status: string;
	@column()
	declare timezone: string;
	@column.dateTime()
	declare toDate: DateTime | null;
}

export class TenantMembershipSchema extends BaseModel {
	static $columns = [
		"createdAt",
		"id",
		"role",
		"tenantId",
		"updatedAt",
		"userId",
	] as const;
	$columns = TenantMembershipSchema.$columns;
	@column.dateTime({ autoCreate: true })
	declare createdAt: DateTime;
	@column({ isPrimary: true })
	declare id: string;
	@column()
	declare role: string;
	@column()
	declare tenantId: string;
	@column.dateTime({ autoCreate: true, autoUpdate: true })
	declare updatedAt: DateTime | null;
	@column()
	declare userId: string;
}

export class TenantSchema extends BaseModel {
	static $columns = [
		"createdAt",
		"id",
		"name",
		"slug",
		"timezone",
		"type",
		"updatedAt",
	] as const;
	$columns = TenantSchema.$columns;
	@column.dateTime({ autoCreate: true })
	declare createdAt: DateTime;
	@column({ isPrimary: true })
	declare id: string;
	@column()
	declare name: string;
	@column()
	declare slug: string;
	@column()
	declare timezone: string;
	@column()
	declare type: string;
	@column.dateTime({ autoCreate: true, autoUpdate: true })
	declare updatedAt: DateTime | null;
}

export class UserSchema extends BaseModel {
	static $columns = [
		"createdAt",
		"email",
		"fullName",
		"id",
		"password",
		"updatedAt",
	] as const;
	$columns = UserSchema.$columns;
	@column.dateTime({ autoCreate: true })
	declare createdAt: DateTime;
	@column()
	declare email: string;
	@column()
	declare fullName: string | null;
	@column({ isPrimary: true })
	declare id: string;
	@column({ serializeAs: null })
	declare password: string;
	@column.dateTime({ autoCreate: true, autoUpdate: true })
	declare updatedAt: DateTime | null;
}
