/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/styles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Platform-wide tattoo styles */
        get: operations["listStyles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/placements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Platform-wide body placements */
        get: operations["listPlacements"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenants/{tenant}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Tenant slug (also its subdomain). Old slugs resolve as aliases. */
                tenant: components["parameters"]["Tenant"];
            };
            cookie?: never;
        };
        /** Public profile and storefront configuration of a tenant */
        get: operations["getStudio"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenants/{tenant}/artists": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Tenant slug (also its subdomain). Old slugs resolve as aliases. */
                tenant: components["parameters"]["Tenant"];
            };
            cookie?: never;
        };
        /** Visible artists of a tenant */
        get: operations["listArtists"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenants/{tenant}/artists/{artist}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Tenant slug (also its subdomain). Old slugs resolve as aliases. */
                tenant: components["parameters"]["Tenant"];
                /** @description Artist slug */
                artist: string;
            };
            cookie?: never;
        };
        /** One artist by slug */
        get: operations["getArtist"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenants/{tenant}/services": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Tenant slug (also its subdomain). Old slugs resolve as aliases. */
                tenant: components["parameters"]["Tenant"];
            };
            cookie?: never;
        };
        /** Bookable services of a tenant */
        get: operations["listServices"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenants/{tenant}/portfolio": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Tenant slug (also its subdomain). Old slugs resolve as aliases. */
                tenant: components["parameters"]["Tenant"];
            };
            cookie?: never;
        };
        /** Portfolio projects, newest first */
        get: operations["listPortfolio"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenants/{tenant}/availability": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Tenant slug (also its subdomain). Old slugs resolve as aliases. */
                tenant: components["parameters"]["Tenant"];
            };
            cookie?: never;
        };
        /**
         * Bookable slots for an artist and service
         * @description Slots are computed, never stored. The range is clamped to the tenant's minimum notice and booking horizon.
         */
        get: operations["listAvailability"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenants/{tenant}/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Tenant slug (also its subdomain). Old slugs resolve as aliases. */
                tenant: components["parameters"]["Tenant"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit a booking request (guest, no account) */
        post: operations["createBooking"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorResponse: {
            error: {
                /**
                 * @example not_found
                 * @example validation_failed
                 * @example rate_limited
                 * @example slot_unavailable
                 */
                code: string;
                message: string;
                /** @description Field path → messages, for validation errors */
                fields?: {
                    [key: string]: string[];
                };
            };
        };
        TattooStyle: {
            /** @example fine-line */
            slug: string;
            /** @example Fine Line */
            name: string;
        };
        BodyPlacement: {
            /** @example forearm */
            slug: string;
            /** @example Forearm */
            name: string;
        };
        Image: {
            /** Format: uri */
            url: string;
            width: number;
            height: number;
            alt?: string | null;
        };
        Money: {
            /** @description Minor units (cents) */
            amount: number;
            /**
             * @description ISO 4217 code
             * @example USD
             */
            currency: string;
        };
        SocialLink: {
            /** @example instagram */
            platform: string;
            /** Format: uri */
            url: string;
        };
        StorefrontSection: {
            /**
             * @example hero
             * @example portfolio
             * @example services
             */
            type: string;
            props: {
                [key: string]: unknown;
            };
        };
        StorefrontConfiguration: {
            /** @example classic */
            theme: string;
            branding: {
                logo?: components["schemas"]["Image"] | null;
                heroImage?: components["schemas"]["Image"] | null;
                /**
                 * @example {
                 *       "primary": "#111111"
                 *     }
                 */
                colors?: {
                    [key: string]: string;
                };
                font?: string | null;
            };
            sections: components["schemas"]["StorefrontSection"][];
        };
        Studio: {
            /** Format: uuid */
            id: string;
            slug: string;
            /** @enum {string} */
            type: "studio" | "independent";
            name: string;
            description?: string | null;
            /**
             * @description IANA timezone
             * @example Asia/Kathmandu
             */
            timezone: string;
            contact: {
                /** Format: email */
                email: string;
                phone?: string | null;
                address?: string | null;
            };
            socialLinks: components["schemas"]["SocialLink"][];
            storefront: components["schemas"]["StorefrontConfiguration"];
        };
        Artist: {
            /** Format: uuid */
            id: string;
            slug: string;
            name: string;
            bio?: string | null;
            photo?: components["schemas"]["Image"] | null;
            acceptingRequests: boolean;
            /** @description Shown instead of the booking form when not accepting requests */
            closedMessage?: string | null;
            serviceIds: string[];
        };
        Service: {
            /** Format: uuid */
            id: string;
            name: string;
            description?: string | null;
            /** @description Estimated duration */
            durationMinutes: number;
            startingPrice?: components["schemas"]["Money"] | null;
        };
        PortfolioProject: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            artistId: string;
            title: string;
            description?: string | null;
            /** @description Style slug */
            style?: string | null;
            /** @description Placement slug */
            placement?: string | null;
            /** Format: date */
            completedOn?: string | null;
            images: components["schemas"]["Image"][];
        };
        Slot: {
            /** Format: date-time */
            startsAt: string;
            /** Format: date-time */
            endsAt: string;
        };
        BookingRequestInput: {
            /** Format: uuid */
            artistId: string;
            /** Format: uuid */
            serviceId: string;
            /**
             * Format: date-time
             * @description Must be a bookable slot
             */
            startsAt: string;
            customer: {
                name: string;
                /** Format: email */
                email: string;
                phone?: string;
            };
            tattoo: {
                idea: string;
                /** @description Style slug */
                style?: string;
                /** @description Placement slug */
                placement?: string;
                /** @example 10 cm */
                size?: string;
                budget?: string;
            };
            notes?: string;
        };
        BookingReceipt: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            status: "requested";
        };
    };
    responses: {
        /** @description Unknown tenant or resource */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Invalid input */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Too many requests */
        RateLimited: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        /** @description Tenant slug (also its subdomain). Old slugs resolve as aliases. */
        Tenant: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listStyles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Styles */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["TattooStyle"][];
                    };
                };
            };
        };
    };
    listPlacements: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Placements */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["BodyPlacement"][];
                    };
                };
            };
        };
    };
    getStudio: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Tenant slug (also its subdomain). Old slugs resolve as aliases. */
                tenant: components["parameters"]["Tenant"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Studio */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Studio"];
                    };
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listArtists: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Tenant slug (also its subdomain). Old slugs resolve as aliases. */
                tenant: components["parameters"]["Tenant"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Artists */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Artist"][];
                    };
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getArtist: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Tenant slug (also its subdomain). Old slugs resolve as aliases. */
                tenant: components["parameters"]["Tenant"];
                /** @description Artist slug */
                artist: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Artist */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Artist"];
                    };
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listServices: {
        parameters: {
            query?: {
                /** @description Only services this artist offers */
                artistId?: string;
            };
            header?: never;
            path: {
                /** @description Tenant slug (also its subdomain). Old slugs resolve as aliases. */
                tenant: components["parameters"]["Tenant"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Services */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Service"][];
                    };
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listPortfolio: {
        parameters: {
            query?: {
                artistId?: string;
                /** @description Style slug */
                style?: string;
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path: {
                /** @description Tenant slug (also its subdomain). Old slugs resolve as aliases. */
                tenant: components["parameters"]["Tenant"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of projects */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["PortfolioProject"][];
                        nextCursor: string | null;
                    };
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listAvailability: {
        parameters: {
            query: {
                artistId: string;
                serviceId: string;
                /** @description First day (in the tenant's timezone) */
                from?: string;
                /** @description Last day, inclusive (in the tenant's timezone) */
                to?: string;
            };
            header?: never;
            path: {
                /** @description Tenant slug (also its subdomain). Old slugs resolve as aliases. */
                tenant: components["parameters"]["Tenant"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Slots */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Slot"][];
                    };
                };
            };
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationError"];
        };
    };
    createBooking: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Tenant slug (also its subdomain). Old slugs resolve as aliases. */
                tenant: components["parameters"]["Tenant"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    booking: components["schemas"]["BookingRequestInput"];
                    referenceImages?: string[];
                    /** @description Bot-challenge token. Required for browser submissions. */
                    challengeToken?: string;
                };
            };
        };
        responses: {
            /** @description Request received */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["BookingReceipt"];
                    };
                };
            };
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationError"];
            429: components["responses"]["RateLimited"];
        };
    };
}
